In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
sent = [
    "The glass of milk",
    "The glass of juice",
    "The cup of tea",
    "I am a good boy",
    "I am a good developer",
    "Understand the meaning of words",
    "Your videos are good"
]

In [21]:
sent

['The glass of milk',
 'The glass of juice',
 'The cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'Your videos are good']

In [22]:
# Define the vocabulary size
voc_size = 10000

In [23]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[7284, 9169, 6477, 8099],
 [7284, 9169, 6477, 7764],
 [7284, 587, 6477, 366],
 [1965, 7959, 9583, 5676, 3895],
 [1965, 7959, 9583, 5676, 3910],
 [6506, 7284, 3029, 6477, 5235],
 [2057, 8842, 1192, 5676]]

In [24]:
# word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [25]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7284 9169 6477 8099]
 [   0    0    0    0 7284 9169 6477 7764]
 [   0    0    0    0 7284  587 6477  366]
 [   0    0    0 1965 7959 9583 5676 3895]
 [   0    0    0 1965 7959 9583 5676 3910]
 [   0    0    0 6506 7284 3029 6477 5235]
 [   0    0    0    0 2057 8842 1192 5676]]


In [26]:
# feature representation
dim = 10

In [29]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile('adam', 'mse')
model.summary()

c:\Users\yshet\AppData\Local\pypoetry\Cache\virtualenvs\genai-udemy-voh_r-00-py3.11\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[[-0.01819615, -0.04702808,  0.04745248, -0.00589541,
         -0.03160566,  0.02500826,  0.03110895,  0.01959993,
         -0.00863019, -0.0103021 ],
        [-0.01819615, -0.04702808,  0.04745248, -0.00589541,
         -0.03160566,  0.02500826,  0.03110895,  0.01959993,
         -0.00863019, -0.0103021 ],
        [-0.01819615, -0.04702808,  0.04745248, -0.00589541,
         -0.03160566,  0.02500826,  0.03110895,  0.01959993,
         -0.00863019, -0.0103021 ],
        [-0.01819615, -0.04702808,  0.04745248, -0.00589541,
         -0.03160566,  0.02500826,  0.03110895,  0.01959993,
         -0.00863019, -0.0103021 ],
        [ 0.01236943, -0.04048814, -0.04074635,  0.03325904,
         -0.02729733,  0.03377893,  0.00484475, -0.02321255,
          0.02039697,  0.02200499],
        [ 0.02872877,  0.01508199, -0.03988463, -0.02885327,
          0.01727874,  0.04244757,  0.04935494,  0.04785676,
          0.04019704,  0.00138284],
        [ 0.04531622, -0.00294922,  0.03661854, -0.0

In [ ]:
embedded_docs[0]